name: '自動化部署'
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  continuous-delivery:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # for posts's lastmod

      - name: 安裝 Ruby 環境
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
          
      - name: 安裝 Node.js 環境
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 16.17.0
          
      - name: 部署前置作業
        run: yarn install && yarn run install-jekyll
        
      - name: 部署
        run: yarn run deploy
        
